### ISSUE TITLE
Feature tracking

### ISSUE THREAD

**Issue by karitham** [kraudcloud/cli#1]
- [ ] managing the appstore
  - [ ] feed
    - [x] ls
    - [x] create
    - [ ] rm
    - [ ] patch
  - [ ] apps
    - [x] ls
    - [x] push
    - [ ] rm
    - [ ] version
    - [ ] hide/deprecate apps
- [x] adding domains
- [ ] managing users

**Comment by aep** [comment]
~~can we use this thing to deploy compose.yaml?~~
we should use this thing to deploy compose.yaml

- it needs to parse the compose yaml locally to find local images
- upload those images
- then next i guess we should add an endpoint that just takes the full yaml and reuses what we have in k8s?
  not really any point in doing all the individual create calls locally when we already have a full compose thing on server

**Comment by karitham** [comment]
> * it needs to parse the compose yaml locally to find local images
> * upload those images

Upload where? Do we have an undocumented Image Registry somewhere or should I open another issue about it?

**Comment by aep** [comment]
kra push is done now.

could you look into making the actual deployment work now?

i.e. `kra up`


docker compose is hell and confuses customers

**Comment by karitham** [comment]
closing this in favor of individual issues
